production:
  bucket: <%= ENV['PRODUCTION_S3_BUCKET'] %>
  access_key_id: <%= ENV['PRODUCTION_S3_BUCKET'] %>
  secret_access_key: <%= ENV['PRODUCTION_S3_SECRET_KEY'] %>

staging:
  bucket: <%= ENV['STAGING_S3_BUCKET'] %>
  access_key_id: <%= ENV['STAGING_S3_BUCKET'] %>
  secret_access_key: <%= ENV['STAGING_S3_SECRET_KEY'] %>

development:
  bucket: <%= ENV['DEVELOPMENT_S3_BUCKET'] %>
  access_key_id: <%= ENV['DEVELOPMENT_S3_BUCKET'] %>
  secret_access_key: <%= ENV['DEVELOPMENT_S3_SECRET_KEY'] %>
