development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cloudspace_rss_staging
  pool: 50
  username: root
  password: '8DF892JAjdfj2903ijV3lsdf2'
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cloudspace_rss_testing
  pool: 50
  username: root
  password: '8DF892JAjdfj2903ijV3lsdf2'
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['STAGING_MYSQL_DATABASE'] %>
  pool: 50
  username: <%= ENV['STAGING_MYSQL_USERNAME'] %>
  password: <%= ENV['STAGING_MYSQL_PASSWORD'] %>
  host: <%= ENV['STAGING_MYSQL_HOST'] %>
  port: <%= ENV['STAGING_MYSQL_PORT'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['PRODUCTION_MYSQL_DATABASE'] %>
  pool: 50
  username: <%= ENV['PRODUCTION_MYSQL_USERNAME'] %>
  password: <%= ENV['PRODUCTION_MYSQL_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_MYSQL_HOST'] %>
  port: <%= ENV['PRODUCTION_MYSQL_PORT'] %>
