feeds = Feed.create([
  {name: 'Cloudspace Blog',         url: 'http://feeds.feedburner.com/TheCloudspaceBlog', default:true},
  {name: 'Engadget',                url: 'http://www.engadget.com/rss.xml', default:true},
  {name: 'The Verge',               url: 'http://www.theverge.com/rss/index.xml', default:true},
  {name: 'CNN Top Stories',         url: 'http://rss.cnn.com/rss/cnn_topstories.rss', default:true},
  {name: 'CNN World',               url: 'http://rss.cnn.com/rss/cnn_world.rss', default:true},
  {name: 'CNN U.S.',                url: 'http://rss.cnn.com/rss/cnn_us.rss'},
  {name: 'CNN Business',            url: 'http://rss.cnn.com/rss/money_latest.rss'},
  {name: 'CNN Politics',            url: 'http://rss.cnn.com/rss/cnn_allpolitics.rss'},
  {name: 'CNN Crime',               url: 'http://rss.cnn.com/rss/cnn_crime.rss'},
  {name: 'Joel on Software',        url: 'http://www.joelonsoftware.com/rss.xml', default:true},
  {name: 'prolly not funny',        url: 'http://feeds.feedburner.com/prollynotfunny'},
  {name: 'Doctor Cat MD',           url: 'http://doctorcatmd.com/feed', default:true},
  {name: 'Atomic-Robo.com',         url: 'http://www.atomic-robo.com/feed/'},
  {name: 'duss005.com',             url: 'http://feeds.feedburner.com/duss005'},
  {name: 'Ars Technica',            url: 'http://feeds.arstechnica.com/arstechnica/index/'},
  {name: 'Coloring for Grown-ups',  url: 'http://coloringforgrownups.com/rss'},
  {name: 'Crawling Road Blog',      url: 'http://crawlingroad.com/blog/feed/'},
  {name: 'Downtown O-Town',         url: 'http://downtown-otown.com/feed/'},
  {name: 'MyFloridaCFO.com CFO Jeff Atwater', url: 'http://www.myfloridacfo.com/podcasts/xml/podcast.xml'},
  {name: 'Orlando Business News - Local Orlando News | The Orlando Business Journal', url: 'http://feeds.bizjournals.com/bizj_orlando'},
  {name: 'SURVIVING IN ARGENTINA', url: 'http://ferfal.blogspot.com/feeds/posts/default'},
  {name: 'the ORLANDOAN - Events and Things to Do in Orlando', url: 'http://www.theorlandoan.com/feeds/posts/default'},
  {name: 'American Thinker', url: 'http://www.americanthinker.com/index.xml'},
  {name: 'Bicycling is Better', url: 'http://mighkwilson.com/feed/'},
  {name: 'Breitbart Feed', url: 'http://feeds.feedburner.com/BreitbartFeed'},
  {name: 'Conservative Black Chick', url: 'http://conservativeblackchick.com/blog/feed/'},
  {name: 'Drudge Report Feed', url: 'http://feeds.feedburner.com/DrudgeReportFeed'},
  {name: 'Guns Save Lives', url: 'http://gunssavelives.net/feed/'},
  {name: 'Liz Mair Blog', url: 'http://www.lizmair.com/LizMair_blogrss.xml'},
  {name: 'Michelle Malkin', url: 'http://feeds.feedburner.com/michellemalkin/posts'},
  {name: 'Mr. Money Mustache', url: 'http://feeds.feedburner.com/MrMoneyMustache'},
  {name: 'Paul Krugman', url: 'http://krugman.blogs.nytimes.com/feed/'},
  {name: 'Power Line', url: 'http://feeds.powerlineblog.com/powerlineblog/livefeed'},
  {name: 'Reason.com', url: 'http://feeds.feedburner.com/reason/Articles'},
  {name: 'Tenth Amendment Center Blog', url: 'http://blog.tenthamendmentcenter.com/feed/'},
  {name: 'The Art of Manliness', url: 'http://feeds2.feedburner.com/TheArtOfManliness'},
  {name: 'The Last Psychiatrist', url: 'http://thelastpsychiatrist.com/atom.xml'},
  {name: 'The New Shooter Podcast', url: 'http://newshooterpodcast.com/feed/'},
  {name: 'TheDailyCity.com | Orlando\'s Concierge', url: 'http://www.thedailycity.com/feeds/posts/default'},
  {name: 'Zero Hedge', url: 'http://feeds.feedburner.com/zerohedge/feed'},
  {name: 'RealClearDefense - Homepage', url: 'http://www.realcleardefense.com/index.xml'},
  {name: 'Small Wars Council', url: 'http://council.smallwarsjournal.com/external.php'},
  {name: 'Small Wars Journal', url: 'http://smallwarsjournal.com/rss'},
  {name: 'Small Wars Journal Articles', url: 'http://smallwarsjournal.com/rss/articles'},
  {name: 'SWJ Blog', url: 'http://smallwarsjournal.com/rss/blogs'},
  {name: 'Alestic.com', url: 'http://feeds.alestic.com/alestic'},
  {name: 'Amazon Web Services Blog', url: 'http://aws.typepad.com/aws/atom.xml'},
  {name: 'AWS Mobile Blog', url: 'http://mobile.awsblog.com/blog/feed/recentPosts.rss'},
  {name: 'AWS Ruby Blog', url: 'http://ruby.awsblog.com/blog/feed/recentPosts.rss'},
  {name: 'Boxed Ice Blog', url: 'http://blog.boxedice.com/feed/'},
  {name: 'Cloudspace | Blog', url: 'http://www.cloudspace.com/blog/feed/'},
  {name: 'Code as Craft', url: 'http://codeascraft.etsy.com/feed/'},
  {name: 'Coding Horror', url: 'http://feeds.feedburner.com/codinghorror/'},
  {name: 'The Netflix Tech Blog', url: 'http://techblog.netflix.com/feeds/posts/default'},
  {name: 'The Nubby Admin', url: 'http://thenubbyadmin.com/feed/'},
  {name: 'Amazon.com Gold Box Deals', url: 'http://rssfeeds.s3.amazonaws.com/goldbox'},
  {name: 'dealnews - Today\'s Edition', url: 'http://s1.dlnws.com/dealnews/rss/todays-edition.xml'},
  {name: 'gun-deals.com', url: 'http://gun-deals.com/rss.php'},
  {name: 'RSS Feed for Gearxs Daily Deal', url: 'http://www.gearxs.com/rss/gearxs.rss'},
  {name: 'Slick Guns', url: 'http://slickguns.com/rss.xml'},
  {name: 'SlickDeals.net', url: 'http://feeds.feedburner.com/SlickdealsnetFP'},
  {name: 'Woot', url: 'http://woot.com/blog/feed.rss'},
  {name: 'Achewood', url: 'http://achewood.com/rss.php'},
  {name: 'chainsawsuit by kris straub', url: 'http://chainsawsuit.com/feed'},
  {name: 'Eat That Toast!', url: 'http://eatthattoast.com/feed/'},
  {name: 'Explosm.net', url: 'http://feeds.feedburner.com/Explosm'},
  {name: 'garfield minus garfield', url: 'http://garfieldminusgarfield.net/rss'},
  {name: 'Gun Show ~ ~ ~ ~', url: 'http://www.rsspect.com/rss/gunshowcomic.xml'},
  {name: 'Married To The Sea', url: 'http://www.marriedtothesea.com/rss/rss.php'},
  {name: 'Natalie Dee', url: 'http://www.nataliedee.com/rss/rss.php'},
  {name: 'Nedroid Picture Diary 2', url: 'http://nedroid.com/feed/'},
  {name: 'Pointless Conversations', url: 'http://www.pointlessconversations.com/rss.xml'},
  {name: 'The Duffel Blog', url: 'http://feeds.feedburner.com/duffelblog'},
  {name: 'The Perry Bible Fellowship', url: 'http://pbfcomics.com/feed/feed.xml'},
  {name: 'The Perry Bible Fellowship', url: 'http://www.pbfcomics.sciesnet.net/feed/feed.xml'},
  {name: 'Three Word Phrase', url: 'http://www.threewordphrase.com/rss.xml'},
  {name: 'Harper\'s Magazine', url: 'http://www.harpers.org/xml/feed/rss.xml'},
  {name: 'The Atlantic', url: 'http://interglacial.com/rss/atlantic_free.rss'},
  {name: 'National Geographic Magazine', url: 'http://www7.nationalgeographic.com/ngm/ngm.xml'},
  {name: 'National Geographic News ', url: 'http://news.nationalgeographic.com/index.rss'},
  {name: 'MIT Research News - Humanities', url: 'http://web.mit.edu/newsoffice/topic/mithumanities-rss.xml'},
  {name: 'MIT Research News - Literature, languages and writing', url: 'http://web.mit.edu/newsoffice/topic/mitliterature-languages-rss.xml'},
  {name: 'MIT Research News - Innovation and inventions', url: 'http://web.mit.edu/newsoffice/topic/mitinnovation-rss.xml'},
  {name: 'MIT Research News - Security studies and military', url: 'http://web.mit.edu/newsoffice/topic/mitsecurity-studies-rss.xml'},
  {name: 'MIT Research News - Urban studies and planning', url: 'http://web.mit.edu/newsoffice/topic/miturban-studies-rss.xml'},
  {name: 'NPR Race', url: 'http://www.npr.org/rss/rss.php?id=1015'},
  {name: 'NPR Interviews', url: 'http://www.npr.org/rss/rss.php?id=1022'},
  {name: 'Time Magazine Photo Essays', url: 'http://rss.time.com/web/time/rss/photoessays/index.xml'},
  {name: 'Time Pictured', url: 'http://rss.time.com/web/time/rss/pictured/index.xml'},
  {name: 'Urban Cartography', url: 'http://www.urbancartography.com/index.rdf'},
  {name: 'Washington Post Religion', url: 'http://www.washingtonpost.com/wp-dyn/rss/metro/religion/index.xml'},
  {name: 'NPR Religion', url: 'http://www.npr.org/rss/rss.php?id=1016'},
  {name: 'NPR Media', url: 'http://www.npr.org/rss/rss.php?id=1020'},
  {name: 'CNN Law', url: 'http://rss.cnn.com/rss/cnn_law.rss'},
  {name: 'EDGAR Index Free SEC Filing Directory', url: 'http://dir.edgarindex.com/index.asp'},
  {name: 'NPR Legal Affairs', url: 'http://www.npr.org/rss/rss.php?id=1070'},
  {name: 'Exhibitions at the NY Public Library (Research Libraries)', url: 'http://www.nypl.org/rss/rexhibitions.xml'},
  {name: 'Exhibitions at the NY Public Library (Branch Libraries)', url: 'http://www.nypl.org/rss/bexhibitions.xml'},
  {name: 'Events at the NY Public Library', url: 'http://www.nypl.org/rss/events.xml'},
  {name: 'Art and Design News from LuckyPix', url: 'http://www.luckypix.com/MT/index.rdf'},
  {name: 'London Review of Books', url: 'http://www.lrb.co.uk/homerss.xml'},
  {name: 'NPR Arts & Culture', url: 'http://www.npr.org/rss/rss.php?id=1008'},
  {name: 'Village Voice Arts section', url: 'http://villagevoice.com/rss/arts.rss.xml'},
  {name: 'Guardian Unlimited Arts', url: 'http://www.guardian.co.uk/rssfeed/0,,6,00.xml'},
  {name: 'Guardian Unlimited Books', url: 'http://www.guardian.co.uk/rssfeed/0,,10,00.xml'},
  {name: 'NPR Performing Arts', url: 'http://www.npr.org/rss/rss.php?id=1046'},
  {name: 'NPR Visual Arts', url: 'http://www.npr.org/rss/rss.php?id=1047'},
  {name: 'NPR Visual Culture', url: 'http://www.npr.org/rss/rss.php?id=1049'},
  {name: 'NY Times Arts', url: 'http://www.nytimes.com/services/xml/rss/nyt/Arts.xml'},
  {name: 'NY Times Design', url: 'http://www.nytimes.com/services/xml/rss/nyt/ArtandDesign.xml'},
  {name: 'NY Times Books', url: 'http://www.nytimes.com/services/xml/rss/nyt/Books.xml'},
  {name: 'NY Times Books Review', url: 'http://www.nytimes.com/services/xml/rss/nyt/SundayBookReview.xml'},
  {name: 'NY Times Theater', url: 'http://www.nytimes.com/services/xml/rss/nyt/Theater.xml'},
  {name: 'Washington Post Books', url: 'http://www.washingtonpost.com/wp-dyn/rss/artsandliving/books/index.xml'},
  {name: 'NPR Authors', url: 'http://www.npr.org/rss/rss.php?id=1033'},
  {name: 'NPR Books', url: 'http://www.npr.org/rss/rss.php?id=1032'},
  {name: 'MIT Research News - Architecture', url: 'http://web.mit.edu/newsoffice/topic/mitarchitecture-rss.xml'},
  {name: 'MIT Research News - Media Lab / media arts and sciences', url: 'http://web.mit.edu/newsoffice/topic/mitmedia-lab-rss.xml'},
  {name: 'MIT Research News - Music / music technology', url: 'http://web.mit.edu/newsoffice/topic/mitmusic-rss.xml'},
  {name: 'Guardian Unlimited Culture Vulture', url: 'http://blogs.guardian.co.uk/culturevulture/index.rdf'},
  {name: 'Cartoon Modern', url: 'http://cartoonmodern.blogsome.com/feed/'},
  {name: 'Daily New Yorker Cartoon', url: 'http://interglacial.com/rss/new_yorker_cartoon.rss'},
  {name: 'For Better or For Worse ', url: 'http://www.fborfw.com/strip_fix/index.xml'},
  {name: 'Piled Higher and Deeper', url: 'http://www.phdcomics.com/gradfeed.php'},
  {name: 'Dilbert ', url: 'http://www.tapestrycomics.com/dilbert.xml'},
  {name: 'NY Times Fashion & Style', url: 'http://www.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml'},
  {name: 'NY Times Thursday Styles', url: 'http://www.nytimes.com/services/xml/rss/nyt/ThursdayStyles.xml'},
  {name: 'NY Times Sunday Styles', url: 'http://www.nytimes.com/services/xml/rss/nyt/SundayStyles.xml'},
  {name: 'NY Times Weddings', url: 'http://www.nytimes.com/services/xml/rss/nyt/Weddings.xml'},
  {name: 'Washington Post Style', url: 'http://www.washingtonpost.com/wp-dyn/rss/print/style/index.xml'},
  {name: 'Movie reviews from NPR', url: 'http://www.npr.org/rss/rss.php?id=4467349'},
  {name: 'Village Voice Film section', url: 'http://villagevoice.com/rss/film.rss.xml'},
  {name: 'Guardian Unlimited Film news', url: 'http://www.guardian.co.uk/rssfeed/0,,16,00.xml'},
  {name: 'NY Times Movie News', url: 'http://www.nytimes.com/services/xml/rss/nyt/MovieNews.xml'},
  {name: 'NY Times Movie Reviews', url: 'http://www.nytimes.com/services/xml/rss/nyt/Movies.xml'},
  {name: 'NY Times Movies - Red Carpet', url: 'http://www.nytimes.com/services/xml/rss/nyt/RedCarpet.xml'},
  {name: 'NPR Movies', url: 'http://www.npr.org/rss/rss.php?id=1045'},
  {name: 'Rotten Tomatoes News Headlines', url: 'http://i.rottentomatoes.com/syndication/rss/top_news.xml'},
  {name: 'Rotten Tomatoes In Theaters', url: 'http://i.rottentomatoes.com/syndication/rss/in_theaters.xml'},
  {name: 'Rotten Tomatoes Top Movies', url: 'http://i.rottentomatoes.com/syndication/rss/top_movies.xml'},
  {name: 'Rotten Tomatoes Certified Fresh Movie', url: 'http://i.rottentomatoes.com/syndication/rss/movie_certified_fresh.xml'},
  {name: 'Rotten Tomatoes Top DVDs', url: 'http://i.rottentomatoes.com/syndication/rss/top_dvds.xml'},
  {name: 'Rotten Tomatoes New DVD Releases', url: 'http://i.rottentomatoes.com/syndication/rss/new_releases.xml'},
  {name: 'Rolling Stone Reviews: Movies', url: 'http://www.rollingstone.com/rssxml/movie_reviews.xml'},
  {name: 'Rolling Stone Reviews: DVDs', url: 'http://www.rollingstone.com/rssxml/dvd_reviews.xml'},
  {name: 'Village Voice Music section', url: 'http://villagevoice.com/rss/music.rss.xml'},
  {name: 'BBC News Entertainment', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/entertainment/rss.xml'},
  {name: 'NPR Music', url: 'http://www.npr.org/rss/rss.php?id=1039'},
  {name: 'NPR Music: Classical Music', url: 'http://www.npr.org/rss/rss.php?id=1041'},
  {name: 'NPR Music: Jazz', url: 'http://www.npr.org/rss/rss.php?id=1042'},
  {name: 'NPR Music: Live at NPR', url: 'http://www.npr.org/rss/rss.php?id=1040'},
  {name: 'NPR Music: Pop Music', url: 'http://www.npr.org/rss/rss.php?id=1043'},
  {name: 'NPR Music: World Music', url: 'http://www.npr.org/rss/rss.php?id=1044'},
  {name: 'NPR Pop Culture', url: 'http://www.npr.org/rss/rss.php?id=1048'},
  {name: 'NY Times Music', url: 'http://www.nytimes.com/services/xml/rss/nyt/Music.xml'},
  {name: 'NY Times Television News', url: 'http://www.nytimes.com/services/xml/rss/nyt/Television.xml'},
  {name: 'Rolling Stone Music News', url: 'http://www.rollingstone.com/rssxml/music_news.xml'},
  {name: 'Rolling Stone Reviews: CDs', url: 'http://www.rollingstone.com/rssxml/album_reviews.xml'},
  {name: 'Rolling Stone Photos', url: 'http://www.rollingstone.com/rssxml/photos.xml'},
  {name: 'Rolling Stone Videos', url: 'http://www.rollingstone.com/rssxml/videos.xml'},
  {name: 'People Magazine Celebrity Photos', url: 'http://rss.people.com/web/people/rss/photogalleries/index.xml'},
  {name: 'US Magazine Celebrity News', url: 'http://www.usmagazine.com/this_minute/feed'},
  {name: 'Guardian Unlimited Football', url: 'http://www.guardian.co.uk/rssfeed/0,,5,00.xml'},
  {name: 'Guardian Unlimited Sport', url: 'http://www.guardian.co.uk/rssfeed/0,,7,00.xml'},
  {name: 'NY Times Sports ', url: 'http://www.nytimes.com/services/xml/rss/nyt/Sports.xml'},
  {name: 'NY Times College Basketball', url: 'http://www.nytimes.com/services/xml/rss/nyt/CollegeBasketball.xml'},
  {name: 'NY Times College Football', url: 'http://www.nytimes.com/services/xml/rss/nyt/CollegeFootball.xml'},
  {name: 'NY Times Golf', url: 'http://www.nytimes.com/services/xml/rss/nyt/Golf.xml'},
  {name: 'NY Times Hockey', url: 'http://www.nytimes.com/services/xml/rss/nyt/Hockey.xml'},
  {name: 'NY Times Other Sports', url: 'http://www.nytimes.com/services/xml/rss/nyt/OtherSports.xml'},
  {name: 'NY Times Pro Baseball', url: 'http://www.nytimes.com/services/xml/rss/nyt/Baseball.xml'},
  {name: 'NY Times Pro Basketball', url: 'http://www.nytimes.com/services/xml/rss/nyt/ProBasketball.xml'},
  {name: 'NY Times Pro Football', url: 'http://www.nytimes.com/services/xml/rss/nyt/ProFootball.xml'},
  {name: 'NY Times Soccer', url: 'http://www.nytimes.com/services/xml/rss/nyt/Soccer.xml'},
  {name: 'Washington Post Sports', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index.xml'},
  {name: 'Washington Post NFL', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index/nfl/index.xml'},
  {name: 'Washington Post NBA', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index/nba/index.xml'},
  {name: 'Washington Post MLB', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index/mlb/index.xml'},
  {name: 'Washington Post MLS', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index/mls/index.xml'},
  {name: 'Washington Post NHL', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index/nhl/index.xml'},
  {name: 'Washington Post WNBA', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/index/wnba/index.xml'},
  {name: 'Washington Post College Football', url: 'http://www.washingtonpost.com/wp-dyn/rss/sports/colleges/football/index.xml'},
  {name: 'NPR Sports', url: 'http://www.npr.org/rss/rss.php?id=1055'},
  {name: 'National Geographic Traveler', url: 'http://nationalgeographic.com/traveler/ngt.xml'},
  {name: 'National Geographic Adventure', url: 'http://nationalgeographic.com/adventure/nga.xml'},
  {name: 'NY Times Travel', url: 'http://www.nytimes.com/services/xml/rss/nyt/Travel.xml'},
  {name: 'NY Times Escapes', url: 'http://www.nytimes.com/services/xml/rss/nyt/Escapes.xml'},
  {name: 'GoArticles Travel', url: 'http://www.goarticles.com/cgi-bin/rss-search.cgi?l=20&s=1&c=58&D1=subject&title=Travel'},
  {name: 'NY Times Real Estate ', url: 'http://www.nytimes.com/services/xml/rss/nyt/RealEstate.xml'},
  {name: 'NY Times Home & Garden ', url: 'http://www.nytimes.com/services/xml/rss/nyt/HomeandGarden.xml'},
  {name: 'Washington Post Real Estate', url: 'http://www.washingtonpost.com/wp-dyn/rss/realestate/index.xml'},
  {name: 'Washington Post DC Area Living', url: 'http://www.washingtonpost.com/wp-dyn/rss/realestate/dcarealiving/index.xml'},
  {name: 'Washington Post Home Improvement', url: 'http://www.washingtonpost.com/wp-dyn/rss/realestate/own/index.xml'},
  {name: 'Interior Design Magazine ', url: 'http://www.interiordesign.net/IDNews.xml'},
  {name: 'GoArticles Home Repair', url: 'http://www.goarticles.com/cgi-bin/rss-search.cgi?l=20&s=1&c=25&D1=subject&title=Home+Repair'},
  {name: 'GoArticles Gardening', url: 'http://www.goarticles.com/cgi-bin/rss-search.cgi?l=20&s=1&c=69&D1=subject&title=Gardening'},
  {name: 'Kitchen Window - recipes and food commentary from NPR ', url: 'http://www.npr.org/rss/rss.php?id=4578972'},
  {name: 'Recipe of the Day from Recipe Center ', url: 'http://www.bhg.com/external/bhg/recipe/rss/rss_2.0_RSS_RECIPE_OF_THE_DAY.xml'},
  {name: 'Diabetic Recipes ', url: 'http://www.bhg.com/external/bhg/recipe/rss/rss_2.0_182.xml;jsessionid=5P3HMZLJF2UQDQFIBQSB42Q'},
  {name: 'Quick & Easy Recipes', url: 'http://www.bhg.com/external/bhg/recipe/rss/rss_2.0_8.xml;jsessionid=5P3HMZLJF2UQDQFIBQSB42Q'},
  {name: 'Low Fat Recipes', url: 'http://www.bhg.com/external/bhg/recipe/rss/rss_2.0_15.xml;jsessionid=5P3HMZLJF2UQDQFIBQSB42Q'},
  {name: 'Kids\' Favorites', url: 'http://www.bhg.com/external/bhg/recipe/rss/rss_2.0_13.xml;jsessionid=5P3HMZLJF2UQDQFIBQSB42Q'},
  {name: 'Allrecipes.com Dinner Recipes', url: 'http://rss.allrecipes.com/2/3.xml'},
  {name: 'Allrecipes.com Healthy Recipes', url: 'http://rss.allrecipes.com/2/7.xml'},
  {name: 'Allrecipes.com Entertaining Recipes', url: 'http://rss.allrecipes.com/2/6.xml'},
  {name: 'Allrecipes.com Baking Recipes', url: 'http://rss.allrecipes.com/2/1.xml'},
  {name: 'NY Times Dining & Wine', url: 'http://www.nytimes.com/services/xml/rss/nyt/DiningandWine.xml'},
  {name: 'NPR Food', url: 'http://www.npr.org/rss/rss.php?id=1053'},
  {name: 'Blogging Baby ', url: 'http://www.bloggingbaby.com/rss.xml'},
  {name: 'NPR Children\'s Health', url: 'http://www.npr.org/rss/rss.php?id=1030'},
  {name: 'NY Times Education ', url: 'http://www.nytimes.com/services/xml/rss/nyt/Education.xml'},
  {name: 'Education Guardian', url: 'http://www.guardian.co.uk/rssfeed/0,,8,00.xml'},
  {name: 'Washington Post Education', url: 'http://www.washingtonpost.com/wp-dyn/rss/education/index.xml'},
  {name: 'Washington Post "Class Struggle"', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400611.xml'},
  {name: 'NPR Education', url: 'http://www.npr.org/rss/rss.php?id=1013'},
  {name: 'Time Daily Rx', url: 'http://rss.time.com/web/time/rss/rss_dailyrx.xml'},
  {name: 'NY Times Health ', url: 'http://www.nytimes.com/services/xml/rss/nyt/Health.xml'},
  {name: 'NY Times Fitness and Nutrition', url: 'http://www.nytimes.com/services/xml/rss/nyt/Nutrition.xml'},
  {name: 'NY Times Health Policy', url: 'http://www.nytimes.com/services/xml/rss/nyt/HealthCarePolicy.xml'},
  {name: 'NY Times Mental Health & Behavior', url: 'http://www.nytimes.com/services/xml/rss/nyt/Psychology.xml'},
  {name: 'Popular Science Magazine Medicine', url: 'http://rss.popsci.com/web/popsci/rss/medicine/index.xml'},
  {name: 'BBC News Health', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/health/rss.xml'},
  {name: 'Washington Post Health', url: 'http://www.washingtonpost.com/wp-dyn/rss/health/index.xml'},
  {name: 'Washington Post Lean Plate Club', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/25/LI2005032500803.xml'},
  {name: 'Washington Post Moving Crew', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/25/LI2005032500785.xml'},
  {name: 'Washington Post Quick Study', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/25/LI2005032500698.xml'},
  {name: 'NPR Health Care', url: 'http://www.npr.org/rss/rss.php?id=1027'},
  {name: 'EarthWire/UK News', url: 'http://www.earthwire.org/feeds/getnews_uk_rss.xml'},
  {name: 'NPR Environment', url: 'http://www.npr.org/rss/rss.php?id=1025'},
  {name: 'MIT Research News - Earth and atmospheric sciences', url: 'http://web.mit.edu/newsoffice/topic/mitearth-atmosphere-rss.xml'},
  {name: 'MIT Research News - Environment', url: 'http://web.mit.edu/newsoffice/topic/mitenvironment-rss.xml'},
  {name: 'MIT Research News - Energy', url: 'http://web.mit.edu/newsoffice/topic/mitenergy-rss.xml'},
  {name: 'Science Magazine Current Issue ', url: 'http://www.sciencemag.org/rss/current.xml'},
  {name: 'Science Magazine News Summaries ', url: 'http://www.sciencemag.org/rss/news.xml'},
  {name: 'This Week in Science', url: 'http://www.sciencemag.org/rss/twis.xml'},
  {name: 'Science Magazine\'s NetWatch -- Best of the Web in science', url: 'http://www.sciencemag.org/rss/nw.xml'},
  {name: 'ScienceNOW Daily Headlines', url: 'http://sciencenow.sciencemag.org/rss/current.xml'},
  {name: 'Guardian Unlimited Science', url: 'http://www.guardian.co.uk/rssfeed/0,,18,00.xml'},
  {name: 'NY Times Science', url: 'http://www.nytimes.com/services/xml/rss/nyt/Science.xml'},
  {name: 'NY Times Earth', url: 'http://www.nytimes.com/services/xml/rss/nyt/Environment.xml'},
  {name: 'BBC News Science/Nature', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/science/nature/rss.xml'},
  {name: 'Washington Post Science', url: 'http://www.washingtonpost.com/wp-dyn/rss/nation/science/index.xml'},
  {name: 'NPR Health & Science', url: 'http://www.npr.org/rss/rss.php?id=1007'},
  {name: 'NPR Research News', url: 'http://www.npr.org/rss/rss.php?id=1024'},
  {name: 'MIT Research News - Biology, biotechnology and genetics ', url: 'http://web.mit.edu/newsoffice/topic/mitbiology-rss.xml'},
  {name: 'MIT Research News - Chemistry and chemical engineering', url: 'http://web.mit.edu/newsoffice/topic/mitchemistry-rss.xml'},
  {name: 'MIT Research News - Civil engineering', url: 'http://web.mit.edu/newsoffice/topic/mitcivil-engineering-rss.xml'},
  {name: 'MIT Research News - Health sciences and technology', url: 'http://web.mit.edu/newsoffice/topic/mithealth-rss.xml'},
  {name: 'MIT Research News - Materials science', url: 'http://web.mit.edu/newsoffice/topic/mitmaterials-science-rss.xml'},
  {name: 'MIT Research News - Mathematics', url: 'http://web.mit.edu/newsoffice/topic/mitmathematics-rss.xml'},
  {name: 'MIT Research News - Mechanical engineering', url: 'http://web.mit.edu/newsoffice/topic/mitmechanical-engineering-rss.xml'},
  {name: 'MIT Research News - Neuroscience', url: 'http://web.mit.edu/newsoffice/topic/mitneuroscience-rss.xml'},
  {name: 'MIT Research News - Nuclear engineering', url: 'http://web.mit.edu/newsoffice/topic/mitnuclear-engineering-rss.xml'},
  {name: 'MIT Research News - Oceanography and ocean engineering', url: 'http://web.mit.edu/newsoffice/topic/mitoceans-rss.xml'},
  {name: 'MIT Research News - Physics', url: 'http://web.mit.edu/newsoffice/topic/mitphysics-rss.xml'},
  {name: 'Popular Science Magazine Top Stories', url: 'http://rss.popsci.com/web/popsci/rss/topstories/index.xml'},
  {name: 'Wall Street Journal Personal Technology/Walt Mossberg (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7071.xml'},
  {name: 'NASA Breaking News', url: 'http://www.nasa.gov/rss/breaking_news.rss'},
  {name: 'NASA Image of the Day', url: 'http://www.nasa.gov/rss/image_of_the_day.rss'},
  {name: 'Science@NASA', url: 'http://www.nasa.gov/rss/science_at_nasa.rss'},
  {name: 'NASA Earth Observatory', url: 'http://earthobservatory.nasa.gov/eo.rss'},
  {name: 'NASA Space Research News', url: 'http://spaceresearch.nasa.gov/news/obprnews.rdf'},
  {name: 'NY Times Space', url: 'http://www.nytimes.com/services/xml/rss/nyt/Space.xml'},
  {name: 'NPR Space', url: 'http://www.npr.org/rss/rss.php?id=1026'},
  {name: 'MIT Research News - Aeronautical and astronautical engineering', url: 'http://web.mit.edu/newsoffice/topic/mitaeronautics-rss.xml'},
  {name: 'MIT Research News - Space, astronomy and planetary science', url: 'http://web.mit.edu/newsoffice/topic/mitspace-rss.xml'},
  {name: 'Popular Science Magazine Aviation & Space', url: 'http://rss.popsci.com/web/popsci/rss/aviationspace/index.xml'},
  {name: 'Guardian Unlimited Technology', url: 'http://www.guardian.co.uk/rssfeed/0,,20,00.xml'},
  {name: 'NY Times Technology ', url: 'http://www.nytimes.com/services/xml/rss/nyt/Technology.xml'},
  {name: 'NY Times Automobiles', url: 'http://www.nytimes.com/services/xml/rss/nyt/Automobiles.xml'},
  {name: 'BBC News Technology', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/technology/rss.xml'},
  {name: 'Washington Post Technology', url: 'http://www.washingtonpost.com/wp-dyn/rss/technology/index.xml'},
  {name: 'Washington Post Tech Policy', url: 'http://www.washingtonpost.com/wp-dyn/rss/technology/techpolicy/index.xml'},
  {name: 'Wall Street Journal Technology News (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7015.xml'},
  {name: 'MIT Research News - Computer science and technology', url: 'http://web.mit.edu/newsoffice/topic/mitcomputers-rss.xml'},
  {name: 'MIT Research News - Electrical engineering and electronics', url: 'http://web.mit.edu/newsoffice/topic/mitelectrical-engineering-rss.xml'},
  {name: 'MIT Research News - Nanoscience and nanotechnology', url: 'http://web.mit.edu/newsoffice/topic/mitnanotech-rss.xml'},
  {name: 'MIT Research News - Robotics / artificial intelligence', url: 'http://web.mit.edu/newsoffice/topic/mitrobotics-rss.xml'},
  {name: 'MIT Research News - Technology and society', url: 'http://web.mit.edu/newsoffice/topic/mittechnology-society-rss.xml'},
  {name: 'Popular Science Magazine General Technology', url: 'http://rss.popsci.com/web/popsci/rss/technology/generaltechnology/index.xml'},
  {name: 'Newsweek Technology - Brad Stone', url: 'http://rss.msnbc.msn.com/id/6073321/device/rss/rss.xml'},
  {name: 'NPR Technology', url: 'http://www.npr.org/rss/rss.php?id=1019'},
  {name: 'CIO News Alerts', url: 'http://www.cio.com/rss_files/editorial_1.xml'},
  {name: 'Gamedownloads.com top 20 recent downloads', url: 'http://www.gamedownloads.com/xml/all.xml'},
  {name: 'InfoWorld: Top News', url: 'http://www.infoworld.com/rss/news.xml'},
  {name: 'Macworld', url: 'http://www.macworld.com/rss.xml'},
  {name: 'Network World NetFlash', url: 'http://www.networkworld.com/netflash.rss'},
  {name: 'Playlist Features/Reviews', url: 'http://playlistmag.com/features/rss.xml'},
  {name: 'Techworld.com', url: 'http://www.techworld.com/rss/techworld.xml'},
  {name: 'The Wireless Report', url: 'http://www.thewirelessreport.com/rss.xml'},
  {name: 'Digital Camera reviews from Dpreview.com', url: 'http://www.dpreview.com/news/dpr.rdf'},
  {name: 'Cnet.com Reviews - Most Recent Computer Systems', url: 'http://reviews.cnet.com/4924-3000_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Desktops', url: 'http://reviews.cnet.com/4924-3118_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Handhelds', url: 'http://reviews.cnet.com/4924-3127_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Camcorders', url: 'http://reviews.cnet.com/4924-6500_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Cell Phones', url: 'http://reviews.cnet.com/4924-3504_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Home Audio', url: 'http://reviews.cnet.com/4924-6462_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Peripherals', url: 'http://reviews.cnet.com/4924-3132_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Notebooks', url: 'http://reviews.cnet.com/4924-3121_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Digital Cameras', url: 'http://reviews.cnet.com/4924-6501_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Portable Audio', url: 'http://reviews.cnet.com/4924-6450_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Home Video', url: 'http://reviews.cnet.com/4924-6463_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Software', url: 'http://reviews.cnet.com/4924-3513_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'Cnet.com Reviews - Most Recent Networking and Wireless', url: 'http://reviews.cnet.com/4924-3243_7-0.xml?orderBy=-7rvDte&7rType=70-80&maxhits=10'},
  {name: 'PC World Magazine Latest News', url: 'http://rss.pcworld.com/rss/latestnews.rss'},
  {name: 'PC World Magazine Techlog', url: 'http://blogs.pcworld.com/techlog/index.rss'},
  {name: 'Today @ PC World', url: 'http://blogs.pcworld.com/staffblog/index.rss'},
  {name: 'PC World Magazine Most Popular Downloads of the Week', url: 'http://rss.pcworld.com/rss/downloads.rss?period=week'},
  {name: 'PC World Magazine Most Popular Downloads of the Month', url: 'http://rss.pcworld.com/rss/downloads.rss?period=month'},
  {name: 'Slashdot.org main feed', url: 'http://rss.slashdot.org/Slashdot/slashdot'},
  {name: 'Slashdot.org book reviews ', url: 'http://rss.slashdot.org/Slashdot/slashdotBookReviews'},
  {name: 'Slashdot.org news for developers ', url: 'http://rss.slashdot.org/Slashdot/slashdotDevelopers'},
  {name: 'Slashdot.org apple news ', url: 'http://rss.slashdot.org/Slashdot/slashdotApple'},
  {name: 'Slashdot.org game news', url: 'http://rss.slashdot.org/Slashdot/slashdotGames'},
  {name: 'Slashdot.org hardware news ', url: 'http://rss.slashdot.org/Slashdot/slashdotHardware'},
  {name: 'Slashdot.org interviews', url: 'http://rss.slashdot.org/Slashdot/slashdotInterviews'},
  {name: 'Slashdot.org IT news', url: 'http://rss.slashdot.org/Slashdot/slashdotit'},
  {name: 'Slashdot.org Linux news', url: 'http://rss.slashdot.org/Slashdot/slashdotlinux'},
  {name: 'Slashdot.org politics news', url: 'http://rss.slashdot.org/Slashdot/slashdotpolitics'},
  {name: 'Slashdot.org science news', url: 'http://rss.slashdot.org/Slashdot/slashdotscience'},
  {name: 'Wired Magazine', url: 'http://wired.com/rss/index.xml'},
  {name: 'Webmaster World', url: 'http://www.webmasterworld.com/index.rss'},
  {name: 'Jeremy Zawodny', url: 'http://jeremy.zawodny.com/blog/rss2.xml'},
  {name: 'Matt Cutts', url: 'http://www.mattcutts.com/blog/feed/'},
  {name: '456 Berea Street', url: 'http://www.456bereastreet.com/feed.xml'},
  {name: 'A List Apart ', url: 'http://alistapart.com/rss.xml'},
  {name: 'The Web2.0 Show', url: 'http://feeds.feedburner.com/web20Show'},
  {name: 'NY Times Business Page', url: 'http://www.nytimes.com/services/xml/rss/nyt/Business.xml'},
  {name: 'NY Times Media & Advertising', url: 'http://www.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml'},
  {name: 'NY Times World Business', url: 'http://www.nytimes.com/services/xml/rss/nyt/WorldBusiness.xml'},
  {name: 'NY Times Your Money', url: 'http://www.nytimes.com/services/xml/rss/nyt/YourMoney.xml'},
  {name: 'Guardian Unlimited Business', url: 'http://www.guardian.co.uk/rssfeed/0,,24,00.xml'},
  {name: 'Guardian Unlimited Business Insight', url: 'http://blogs.guardian.co.uk/businessinsight/index.rdf'},
  {name: 'MIT Research News - Business and management', url: 'http://web.mit.edu/newsoffice/topic/mitbusiness-rss.xml'},
  {name: 'MIT Research News - Economics', url: 'http://web.mit.edu/newsoffice/topic/miteconomics-rss.xml'},
  {name: 'Wall Street Journal US Business (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7014.xml'},
  {name: 'Wall Street Journal Market News (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7031.xml'},
  {name: 'Wall Street Journal Opinion - Review & Outlook (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7041.xml'},
  {name: 'Wall Street Journal Media & Marketing (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7020.xml'},
  {name: 'BBC News Business', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/business/rss.xml'},
  {name: 'Washington Post Business', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/index.xml'},
  {name: 'Washington Post Business Policy', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/government/index.xml'},
  {name: 'Washington Post Click & Clack', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400129.xml'},
  {name: 'Washington Post Defense Industry News', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/04/11/LI2005041100380.xml'},
  {name: 'Washington Post Economy', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/economy/index.xml'},
  {name: 'Washington Post Financial Industry News', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/04/18/LI2005041800997.xml'},
  {name: 'Washington Post Industries', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/industries/index.xml'},
  {name: 'Washington Post Investing', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/28/LI2005032800718.xml'},
  {name: 'Washington Post Metro Business', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/localbusiness/index.xml'},
  {name: 'Washington Post Oil and Gas Prices', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/special/3/index.xml'},
  {name: 'Washington Post Pentagon Procurement News', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/special/5/index.xml'},
  {name: 'Washington Post Personal Finance', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/personalfinance/index.xml'},
  {name: 'Washington Post Struggling Airlines', url: 'http://www.washingtonpost.com/wp-dyn/rss/business/special/1/index.xml'},
  {name: 'Washington Post Transportation Industry News', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/04/18/LI2005041801007.xml'},
  {name: 'Washington Post Week in Stocks', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/28/LI2005032800573.xml'},
  {name: 'NPR Business', url: 'http://www.npr.org/rss/rss.php?id=1006'},
  {name: 'NPR Economy', url: 'http://www.npr.org/rss/rss.php?id=1017'},
  {name: 'NPR Personal Finance', url: 'http://www.npr.org/rss/rss.php?id=1018'},
  {name: 'NY Times Homepage', url: 'http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml'},
  {name: 'NY Times Magazine', url: 'http://www.nytimes.com/services/xml/rss/nyt/Magazine.xml'},
  {name: 'Guardian Unlimited front page', url: 'http://www.guardian.co.uk/rssfeed/0,,1,00.xml'},
  {name: 'BBC News Front Page', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/front_page/rss.xml'},
  {name: 'BBC News Magazine', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/uk_news/magazine/rss.xml'},
  {name: 'Washington Post Front Page', url: 'http://www.washingtonpost.com/wp-dyn/rss/print/asection/index.xml'},
  {name: 'Huffington Post Latest News', url: 'http://www.huffingtonpost.com/thenewswire/full_rss.rdf'},
  {name: 'Huffington Post blog contributors', url: 'http://www.huffingtonpost.com/theblog/full_index.rdf'},
  {name: 'Huffington Post featured contributor posts', url: 'http://www.huffingtonpost.com/picks_blog_index.rdf'},
  {name: 'Huffington Post complete feed', url: 'http://www.huffingtonpost.com/raw_feed_index.rdf'},
  {name: 'NPR All Things Considered', url: 'http://www.npr.org/rss/rss.php?id=2'},
  {name: 'NPR Morning Edition', url: 'http://www.npr.org/rss/rss.php?id=3'},
  {name: 'NPR Talk of the Nation', url: 'http://www.npr.org/rss/rss.php?id=5'},
  {name: 'NPR News & Notes with Ed Gordon', url: 'http://www.npr.org/rss/rss.php?id=11'},
  {name: 'NPR Day to Day', url: 'http://www.npr.org/rss/rss.php?id=17'},
  {name: 'NPR Fresh Air with Terry Gross', url: 'http://www.npr.org/rss/rss.php?id=13'},
  {name: 'NPR The Motley Fool Radio Show', url: 'http://www.npr.org/rss/rss.php?id=15'},
  {name: 'NPR Weekend Edition Saturday', url: 'http://www.npr.org/rss/rss.php?id=7'},
  {name: 'NPR Weekend Edition Sunday', url: 'http://www.npr.org/rss/rss.php?id=10'},
  {name: 'NPR World Cafe', url: 'http://www.npr.org/rss/rss.php?id=4724307'},
  {name: 'Wall Street Journal Today\'s Free Features', url: 'http://online.wsj.com/xml/rss/3_7077.xml'},
  {name: 'NY Times International News', url: 'http://www.nytimes.com/services/xml/rss/nyt/International.xml'},
  {name: 'NY Times Africa News', url: 'http://www.nytimes.com/services/xml/rss/nyt/Africa.xml'},
  {name: 'NY Times Americas News', url: 'http://www.nytimes.com/services/xml/rss/nyt/Americas.xml'},
  {name: 'NY Times Asia News', url: 'http://www.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml'},
  {name: 'NY Times Europe News', url: 'http://www.nytimes.com/services/xml/rss/nyt/Europe.xml'},
  {name: 'NY Times Middle East News', url: 'http://www.nytimes.com/services/xml/rss/nyt/MiddleEast.xml'},
  {name: 'BBC News Africa', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/africa/rss.xml'},
  {name: 'BBC News Americas', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/americas/rss.xml'},
  {name: 'BBC News Asia-Pacific', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/asia-pacific/rss.xml'},
  {name: 'BBC News Europe', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/europe/rss.xml'},
  {name: 'BBC News Middle East', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/middle_east/rss.xml'},
  {name: 'BBC News South Asia', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/south_asia/rss.xml'},
  {name: 'BBC News UK', url: 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/uk_news/rss.xml'},
  {name: 'Washington Post World', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/index.xml'},
  {name: 'Washington Post Iraq', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/mideast/iraq/index.xml'},
  {name: 'Washington Post Africa', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/africa/index.xml'},
  {name: 'Washington Post North America', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/northamerica/index.xml'},
  {name: 'Washington Post South America', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/southamerica/index.xml'},
  {name: 'Washington Post Central America', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/centralamerica/index.xml'},
  {name: 'Washington Post Asia/Pacific', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/asia/index.xml'},
  {name: 'Washington Post Europe', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/europe/index.xml'},
  {name: 'Washington Post Middle East', url: 'http://www.washingtonpost.com/wp-dyn/rss/world/mideast/index.xml'},
  {name: 'Newsweek Top Stories International Edition', url: 'http://rss.msnbc.msn.com/id/3037880/device/rss/rss.xml'},
  {name: 'Newsweek World News', url: 'http://rss.msnbc.msn.com/id/3037903/device/rss/rss.xml'},
  {name: 'Newsweek World News - Fareed Zakaria', url: 'http://rss.msnbc.msn.com/id/6639214/device/rss/rss.xml'},
  {name: 'Newsweek World News - Christopher Dickey', url: 'http://rss.msnbc.msn.com/id/3694722/device/rss/rss.xml'},
  {name: 'NPR World News', url: 'http://www.npr.org/rss/rss.php?id=1004'},
  {name: 'NPR Middle East', url: 'http://www.npr.org/rss/rss.php?id=1009'},
  {name: 'Wall Street Journal Europe News (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7012.xml'},
  {name: 'Wall Street Journal Asia News (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7013.xml'},
  {name: 'NY Times National News', url: 'http://www.nytimes.com/services/xml/rss/nyt/National.xml'},
  {name: 'Washington Post Top News', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400102.xml'},
  {name: 'Washington Post Nation', url: 'http://www.washingtonpost.com/wp-dyn/rss/nation/index.xml'},
  {name: 'Washington Post National Security', url: 'http://www.washingtonpost.com/wp-dyn/rss/nation/nationalsecurity/index.xml'},
  {name: 'Washington Post Homeland Security', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400139.xml'},
  {name: 'Washington Post Military', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400140.xml'},
  {name: 'Washington Post Intelligence', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400143.xml'},
  {name: 'Washington Post Courts', url: 'http://www.washingtonpost.com/wp-dyn/rss/linkset/2005/03/24/LI2005032400132.xml'},
  {name: 'Newsweek Top Stories US Edition', url: 'http://rss.msnbc.msn.com/id/3032541/device/rss/rss.xml'},
  {name: 'Newsweek National News', url: 'http://rss.msnbc.msn.com/id/3037898/device/rss/rss.xml'},
  {name: 'Newsweek Terror Watch - Michael Isikoff and Mark Hosenball', url: 'http://rss.msnbc.msn.com/id/3694752/device/rss/rss.xml'},
  {name: 'NPR US News', url: 'http://www.npr.org/rss/rss.php?id=1003'},
  {name: 'Wall Street Journal US News (Subscription Only)', url: 'http://online.wsj.com/xml/rss/3_7011.xml'},
  {name: 'NY Times Washington Section', url: 'http://www.nytimes.com/services/xml/rss/nyt/Washington.xml'},
  {name: 'Washington Post Federal Page', url: 'http://www.washingtonpost.com/wp-dyn/rss/politics/fedpage/index.xml'},
  {name: 'Washington Post Elections', url: 'http://www.washingtonpost.com/wp-dyn/rss/politics/elections/index.xml'},
  {name: 'Washington Post Congress', url: 'http://www.washingtonpost.com/wp-dyn/rss/politics/congress/index.xml'},
  {name: 'Washington Post Bush Administration', url: 'http://www.washingtonpost.com/wp-dyn/rss/politics/administration/index.xml'},
  {name: 'Washington Post Politics', url: 'http://www.washingtonpost.com/wp-dyn/rss/politics/index.xml'},
  {name: 'Newsweek Politics - Howard Fineman', url: 'http://rss.msnbc.msn.com/id/3694738/device/rss/rss.xml'},
  {name: 'Newsweek Politics - Eleanor Clift', url: 'http://rss.msnbc.msn.com/id/3694504/device/rss/rss.xml'},
  {name: 'NPR Politics & Society', url: 'http://www.npr.org/rss/rss.php?id=1012'},
  {name: 'NPR Politics', url: 'http://www.npr.org/rss/rss.php?id=1014'},
  {name: 'NPR Iraq', url: 'http://www.npr.org/rss/rss.php?id=1010'},
  {name: 'Rolling Stone Politics', url: 'http://www.rollingstone.com/rssxml/politics.xml'}, 
  {name: '', url: 'http://feeds.feedburner.com/InvisibleBread', category: 'Web Comics'},
  {name: '', url: 'http://feeds.feedburner.com/crowbarBenson', category: 'Web Comics'},
  {name: '', url: 'http://feeds.feedburner.com/DilbertDailyStrip', category: 'Web Comics'},
  {name: '', url: 'http://feeds.feedburner.com/NotInventedHere', category: 'Web Comics'},
  {name: '', url: 'http://feeds.feedburner.com/2816monument', category: 'Web Comics'},
  {name: '', url: 'http://www.rsspect.com/rss/vagrant.xml', category: 'Web Comics'},
  {name: '', url: 'http://crimesagainsthughsmanatees.tumblr.com/rss', category: 'Web Comics'},
  {name: '', url: 'http://feeds.feedburner.com/kinokofryfeed', category: 'Web Comics'},
  {name: '', url: 'http://allcreatures.tumblr.com/rss', category: 'Pictures'},
  {name: '', url: 'http://dariustwin.tumblr.com/rss', category: 'Pictures'},
  {name: '', url: 'http://feeds.feedburner.com/IzKyoot', category: 'Pictures'},
  {name: '', url: 'http://poppedcultr.tumblr.com/rss', category: 'Pictures'},
  {name: '', url: 'http://feeds.feedburner.com/ComicvineSiteMashup', category: 'Entertainment'},
  {name: '', url: 'http://nerdyshow.com/feed/', category: 'Entertainment'},
  {name: '', url: 'http://feeds.feedburner.com/FutilityCloset', category: 'Entertainment'},
  {name: '', url: 'http://blogs.amctv.com/the-walking-dead/atom.xml', category: 'Entertainment'},
  {name: '', url: 'http://marcusto.tumblr.com/rss', category: 'Entertainment'},
  {name: '', url: 'http://duss005.tumblr.com/rss', category: 'Entertainment'},
  {name: '', url: 'http://textfromdog.tumblr.com/rss', category: 'Entertainment'},
  {name: '', url: 'http://kateordie.tumblr.com/rss', category: 'Entertainment'},
  {name: '', url: 'http://otisthecorgi.com/rss', category: 'Entertainment'},
  {name: '', url: 'http://ourvaluedcustomers.tumblr.com/rss', category: 'Entertainment'},
  {name: '', url: 'http://feeds.feedburner.com/frc', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/firstroundblog', category: 'Technology'},
  {name: '', url: 'http://blog.awe.sm/feed/', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/gnip', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/FeldThoughts', category: 'Technology'},
  {name: '', url: 'http://www.joelonsoftware.com/rss.xml', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/37signals/beMH', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/RidingRails', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/startup/lessons/learned', category: 'Technology'},
  {name: '', url: 'http://codespatter.com/feed/', category: 'Technology'},
  {name: '', url: 'http://www.shirky.com/weblog/feed/', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/cfphp', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/brynary', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/typepad/bijanblog', category: 'Technology'},
  {name: '', url: 'http://feeds.feedburner.com/AVc', category: 'Technology'},  
  {name: '', url: 'http://xkcd.com/rss.xml', category: 'Web Comics'},  
])